version: '3.3'
services:

  api:
    image: neomatrixcode/merly:1.0.2-alpine
    ports:
      - "5000"
    restart: "always"
    networks:
      - "api.network"
    deploy:
      replicas: 5
    volumes:
     - ./app:/app
    command: sh -c "julia app.jl"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "8080:8080"
    networks:
      - "api.network"

networks:
  api.network: